# Generated by Django 5.0 on 2025-01-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_blog', '0002_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/articles/'),
        ),
    ]
